$(document).ready(function(){
  var history = [
    {
      "date":"2019-08-10",
      "location":"store1",
      "orders":[
        {
          "product":"beer1",
          "quantity":"2",
          "price":"5",
          "subtotal":"10"
        },
        {
          "product":"beer2",
          "quantity":"1",
          "price":"7",
          "subtotal":"7"
        }
      ],
      "total":
      {
        "subtotal":"17",
        "tax":"2.21",
        "total":"19.21"
      }
    },
    {
      "date":"2019-07-15",
      "location":"store1",
      "orders":[
        {
          "product":"beer1",
          "quantity":"2",
          "price":"5",
          "subtotal":"10"
        }
      ],
      "total":
      {
        "subtotal":"10",
        "tax":"1.30",
        "total":"11.30"
      }
    },
    {
      "date":"2019-07-12",
      "location":"store1",
      "orders":[
        {
          "product":"beer1",
          "quantity":"2",
          "price":"5",
          "subtotal":"10"
        }
      ],
      "total":
      {
        "subtotal":"10",
        "tax":"1.30",
        "total":"11.30"
      }
    },
    {
      "date":"2019-07-10",
      "location":"store1",
      "orders":[
        {
          "product":"beer1",
          "quantity":"2",
          "price":"5",
          "subtotal":"10"
        }
      ],
      "total":
      {
        "subtotal":"10",
        "tax":"1.30",
        "total":"11.30"
      }
    }
  ]

  $.each(history, function(i, val){
    var $tr = $('<tr><td>'+val["location"]+'</td><td>'+val["date"]+'</td><td>'+val["total"]["total"]+'</td></tr>')
    $('#history-table').append($tr)
  })
})
